name: build

on:
  pull_request:
  push:

jobs:
  create_dev_release:
    runs-on: ubuntu-20.04
    steps:
    - name: Create Development release
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"

  apk:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'false'
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install keystore
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
      shell: bash
      run: |
        base64 -d > keystore.jks <<<"$KEYSTORE"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make android-sdk android-sdk-platform-23

    - name: Build APK
      run: |
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cinny.apk
        path: cinny.apk

    - name: Upload development release
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
      uses: softprops/action-gh-release@v1
      with:
        name: Development Build
        tag_name: "latest"
        prerelease: true
        files: |
          cinny.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload tagged release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
